In [1]:
from sklearn.feature_extraction.text import CountVectorizer 
vect = CountVectorizer(binary = True)

In [2]:
vect = CountVectorizer(binary = True)
#Corpus with 3 documents
corpus = ["NLP is awesome","I want to start a NLP Company","Top unicorns use NLP techniques"]


In [3]:
type(corpus)

list

In [4]:
vect.fit(corpus)

CountVectorizer(binary=True)

In [5]:
#list of unique terms present in the corpus
vocab = vect.vocabulary_

In [6]:
for key in vocab.keys():
    print("{}:{}".format(key,vocab[key]))

nlp:3
is:2
awesome:0
want:10
to:6
start:4
company:1
top:7
unicorns:8
use:9
techniques:5


In [7]:
vect.transform(["I have an awesome NLP Company worth an awesome billion"]).toarray()

array([[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [8]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

def cosine_similarity_text(texts):
    """
    Calculates the cosine similarity between all pairs of texts in a list.
    """
    # create TfidfVectorizer object
    vectorizer = TfidfVectorizer()

    # create sparse matrix of text vectors
    text_vectors = vectorizer.fit_transform(texts)

    # convert sparse matrix to dense matrix
    dense_vectors = text_vectors.todense()

    # calculate cosine similarity
    cos_sim = np.dot(dense_vectors, dense_vectors.T)

    return cos_sim

In [9]:
cos_sim = cosine_similarity_text(corpus)
print(cos_sim)

[[1.         0.10914377 0.10914377]
 [0.10914377 1.         0.08021183]
 [0.10914377 0.08021183 1.        ]]


In [10]:
from sklearn.metrics.pairwise import cosine_similarity 



In [11]:
similarity = cosine_similarity((vect.transform(["ML is an elective subject"]).toarray()),
                               vect.transform(["Airbnb is an NLP company"]).toarray())

In [12]:
print(similarity)

[[0.57735027]]
